### ISSUE TITLE
Blog improvements

### ISSUE THREAD

**Issue by nkshah2** [supertokens/blog#5]
- [x] Add a Github PR action to view a preview of the blog on Netlify
- [x] If someone runs the blog project locally and visits `localhost:8000/` they should either be given a screen with a link to the actual blog landing page (similar to docs) or it should auto redirect to the blog landing page
- [x] Add a Github PR action to check for yarn.lock, the Action should fail if it finds one
- [x] Wrapping in code snippets is not working correctly, for example if the code snippet is `hash()` and the word does not fit, Gatsby renders `has` and `h()` on separate lines
- [x] Styling for inline code snippets do not work correctly in footnotes. If they are part of the content then they render fine
- [x] Add a PR template to the blog directory (Need to discuss all the sections)
    - [x] For new blogs
    - [x] For dev work on the blog project 
- [x] Move the blog issue template from the main-website repo to the blog repo
- [x] Cover images on the `/blog` page should have the correct aspect ratio
- [x] All Gatsby blogs in the blog listing have a link with a trailing `/`, this causes a redirect when we remove the trailing slash. Ideally the listing link should not have a slash
- [ ] By default we dont want all code blocks to wrap to next line if the line goes. beyond the width of the code block (its ok if the user needs to scroll). But in some cases we may want that behaviour (using a code block for variable values for example), in this case there needs to  be a simple way of enabling this behaviour. Ideally we should be able to do this using the markdown code snippet syntax (```) but other solutions that are relatively straightforward also work

# TODO Later

- [ ] Add a Github PR action for spellchecking blogs (If a Grammarly plugin exists then that would be ideal) - https://github.com/supertokens/blog/issues/2
- [ ] Add a Github PR action for making sure that no broken links exist - https://github.com/supertokens/blog/issues/3
- [x] Change the way superscript renders in the blog (slightly bigger and should render with square brackets). For example adding a footnote with `[^1]` by default Gatsby renders it as `<sup>1</sup>`, we want it to render as `<sup>[1]</sup>` (NOTE: We use another plugin for footnotes so this should be compatible with that
- [x] H2 should have a line below it like how it was done in webflow
- [x] Bullet points indentation is not enough

# Good to have(s)

- [ ] On the right side of the blog, there should be a secondary navigation section that allows you to navigate to all the H2 tags in the page (similar to how the docs works)
- [x] Add a feature that enables linking to section titles inside the blog post itself

**Comment by st-jay** [comment]
The checks for meta tag updates and sitemap.xml updates are not added to the PR template as they are a part of the issue template
